export const GlobleConst = {
    emplist: [
        {
            "id": 1,
            "employeeId": "EMP001",
            "firstName": "Rahul",
            "lastName": "Sharma",
            "email": "rahul.sharma@example.com",
            "mobile": "9876543210",
            "department": "IT",
            "designation": "Software Developer",
            "joiningDate": "2023-04-10",
            "salary": 65000,
            "status": "Active"
        },
        {
            "id": 2,
            "employeeId": "EMP002",
            "firstName": "Priya",
            "lastName": "Patil",
            "email": "priya.patil@example.com",
            "mobile": "9876543211",
            "department": "HR",
            "designation": "HR Executive",
            "joiningDate": "2022-08-15",
            "salary": 55000,
            "status": "Active"
        },
        {
            "id": 3,
            "employeeId": "EMP003",
            "firstName": "Amit",
            "lastName": "Deshmukh",
            "email": "amit.deshmukh@example.com",
            "mobile": "9876543212",
            "department": "Finance",
            "designation": "Accountant",
            "joiningDate": "2021-06-20",
            "salary": 58000,
            "status": "Active"
        },
        {
            "id": 4,
            "employeeId": "EMP004",
            "firstName": "Sneha",
            "lastName": "Joshi",
            "email": "sneha.joshi@example.com",
            "mobile": "9876543213",
            "department": "Marketing",
            "designation": "Marketing Executive",
            "joiningDate": "2023-01-12",
            "salary": 60000,
            "status": "Active"
        },
        {
            "id": 5,
            "employeeId": "EMP005",
            "firstName": "Vikas",
            "lastName": "Kulkarni",
            "email": "vikas.kulkarni@example.com",
            "mobile": "9876543214",
            "department": "IT",
            "designation": "Senior Developer",
            "joiningDate": "2020-11-05",
            "salary": 85000,
            "status": "Active"
        },
        {
            "id": 6,
            "employeeId": "EMP006",
            "firstName": "Neha",
            "lastName": "Pawar",
            "email": "neha.pawar@example.com",
            "mobile": "9876543215",
            "department": "Sales",
            "designation": "Sales Executive",
            "joiningDate": "2022-03-18",
            "salary": 52000,
            "status": "Active"
        },
        {
            "id": 7,
            "employeeId": "EMP007",
            "firstName": "Sagar",
            "lastName": "More",
            "email": "sagar.more@example.com",
            "mobile": "9876543216",
            "department": "Operations",
            "designation": "Operations Manager",
            "joiningDate": "2019-09-25",
            "salary": 90000,
            "status": "Active"
        },
        {
            "id": 8,
            "employeeId": "EMP008",
            "firstName": "Pooja",
            "lastName": "Shinde",
            "email": "pooja.shinde@example.com",
            "mobile": "9876543217",
            "department": "Customer Support",
            "designation": "Support Executive",
            "joiningDate": "2023-07-03",
            "salary": 48000,
            "status": "Inactive"
        },
        {
            "id": 9,
            "employeeId": "EMP009",
            "firstName": "Akash",
            "lastName": "Chavan",
            "email": "akash.chavan@example.com",
            "mobile": "9876543218",
            "department": "IT",
            "designation": "UI/UX Designer",
            "joiningDate": "2022-12-01",
            "salary": 70000,
            "status": "Active"
        },
        {
            "id": 10,
            "employeeId": "EMP010",
            "firstName": "Anjali",
            "lastName": "Gaikwad",
            "email": "anjali.gaikwad@example.com",
            "mobile": "9876543219",
            "department": "Administration",
            "designation": "Admin Executive",
            "joiningDate": "2021-02-14",
            "salary": 50000,
            "status": "Active"
        }
    ]
}